pipeline {
    agent none
    stages {
        stage('build') {
            agent {
                docker {
                    image 'python:3-alpine'
                }
            }
            steps {
                sh 'python -m py_compile src/addvals.py src/calc.py'
                stash(name: 'compiled-results', includes: 'src/*.py*')
            }
        }
        stage('test') {
            agent {
                dockerfile {
                    filename 'Dockerfile'
                    dir 'jenkins'
                }
            }
            steps {
                sh 'pytest --junit-xml reports/results.xml src/test_calc.py'
            }
            post {
                always {
                    junit 'reports/results.xml'
                }
            }
        }
    }
}
